name: Java CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_DB: invoice
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Wait for PostgreSQL
        run: |
          for i in {1..10}; do
            pg_isready -h db -p 5432 -U user && echo "Postgres is ready!" && break
            echo "Waiting for postgres..."
            sleep 3
          done

      - name: Build with Gradle
        run: ./gradlew build --no-daemon