name: Docker Compose CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          docker-compose -f tools/docker/docker-compose.yml up -d
          sleep 10  # DBなどの初期化待ち時間（必要に応じて調整）

      - name: Run tests in container
        run: |
          docker-compose -f tools/docker/docker-compose.yml exec -T app ./gradlew test
